server:
  port: 8003

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@metaverse.ohgiraffers.com:1521/xe
    username: C##GAEMIHOUSE
    password: GAEMIHOUSE
  data:
    batch:
      job:
        enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database: oracle